all: myPS myPS2 myPS3 myPS_v0 parsExec

myPS: myPS.c
	gcc myPS.c -o myPS

myPS2: myPS2.c
	gcc myPS2.c -o myPS2

myPS3: myPS3.c
	gcc myPS3.c -o myPS3

myPS_v0: myPS_v0.c
	gcc myPS_v0.c -o myPS_v0

parsExec: parsExec.c
	gcc parsExec.c -o parsExec

clean:
	rm myPS myPS2 myPS3 myPS_v0 parsExec
