all: alarm2 alarm3 ejemplo_signal ejemplo_signal2 eventos eventos2 signal_perdido2

alarm2: ejemplo_alarm2.c
	gcc ejemplo_alarm2.c -o alarm2

alarm3: ejemplo_alarm3.c
	gcc ejemplo_alarm3.c -o alarm3

ejemplo_signal: ejemplo_signal.c
	gcc ejemplo_signal.c -o ejemplo_signal

ejemplo_signal2: ejemplo_signal2.c
	gcc ejemplo_signal2.c -o ejemplo_signal2

eventos: eventos.c
	gcc eventos.c -o eventos

eventos2: eventos2.c
	gcc eventos2.c -o eventos2

signal_perdido2: signal_perdido2.c
	gcc signal_perdido2.c -o signal_perdido2

clean:
	rm alarm2 alarm3 ejemplo_signal ejemplo_signal2 eventos eventos2 signal_perdido2
